version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: currencydb
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - currency_data:/var/lib/postgresql/data

volumes:
    currency_data: